### ISSUE TITLE
Update Flow Log Configuration

### ISSUE THREAD

**Issue by rafikurnia** [traveloka/terraform-aws-vpc#19]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description

AWS just announced that now we can include additional metadata in Amazon VPC flow logs.
We must incorporate the changes into our terraform modules for having a better and easier way of analyzing Flow Logs data. 

Also, reconfigure the delivery to S3 Bucket instead of Cloudwatch will be better due to its cheaper price. 

### New or Affected Resource(s)

* aws_flow_log.this

### Potential Terraform Configuration Changes

https://github.com/traveloka/terraform-aws-vpc/blob/a0677a37746b7f0421dd5396ea84650d052161ba/main.tf#L537-L544

```hcl
```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/09/now-add-additional-metadata-to-amazon-vpc-flow-logs/
* https://github.com/terraform-providers/terraform-provider-aws/issues/10081

**Comment by sumodirjo** [comment]
This also resolved by #26
