### ISSUE TITLE
Allow tagging of VPC and subnets with additional tags

### ISSUE THREAD

**Issue by billnguyentvlk** [traveloka/terraform-aws-vpc#21]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you have submitted a pull request addressing the same issue, please leave a comment!***

***

### Description
**New variables needed to store additional tags for VPC, public subnet, app subnet and data subnet.**

- When EKS runs, it creates some additional Kubernetes tags for resources in VPC. 
- If we apply VPC terraform script again, since these tags are not presented in VPC `tf` script, they will be lost.
- That is why we want to have variables so that we can create the Kubernetes tags upfront and store them in the `tf` script itself. This is also to ensure that `tf` script is the *source of truth* .

### New or Affected Resource(s)

* `aws_vpc`
* `"aws_subnet" "public"`
* `"aws_subnet" "app"`
*  `"aws_subnet" "data"`

### Potential Terraform Configuration Changes

```hcl
variable "additional_vpc_tags" {
  description = "A map of additional tags to add to the vpc"
  default     = {}
}

variable "additional_public_subnet_tags" {
  description = "A map of additional tags to add to the public subnet"
  default     = {}
}

variable "additional_app_subnet_tags" {
  description = "A map of additional tags to add to the application subnet"
  default     = {}
}

variable "additional_data_subnet_tags" {
  description = "A map of additional tags to add to the data subnet"
  default     = {}
}
```

**Comment by SiahaanBernard** [comment]
Hi @billnguyentvlk, thanks for the issue.
I'm curious why do you need additional tags for vpc and subnet, Could you ellaborate more on this? Thanks.

**Comment by billnguyentvlk** [comment]
Hi @SiahaanBernard ,

Thanks for your comment. I have updated the issue description to add more details on why we need these tags. Please help to take a look. Thank you!

**Comment by sshvetsov** [comment]
I think ability to add additional tags on top of required tags for VPC and its subnets has a merit. I have no objections, as long as required tags are not overwritten.
