### ISSUE TITLE
Terraform 12 Behavior Changes

### ISSUE THREAD

**Issue by rizkimhd** [traveloka/terraform-aws-vpc#39]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* ***If you are interested in working on this issue or have submitted a pull request, please leave a comment!***

***

### Summary

[Terraform 12 handle list a bit differently](https://www.terraform.io/upgrade-guides/0-12.html), hence some of the existing outputs will return different result (e.g. list of list instead of list). Hence produce the following error
```
Error: Incorrect attribute value type
  on redundant-list-brackets.tf line 9, in resource "aws_security_group" "foo":
   9:     cidr_blocks = ["${var.cidr_blocks}"]
Inappropriate value for attribute "cidr_blocks": element 0: string required.
```
for the following resources:
```
output "subnet_public_ids" {
  description = "List of IDs of public subnets."
  value       = [aws_subnet.public.*.id]
}
output "subnet_public_cidr_blocks" {
  description = "List of cidr_blocks of public subnets."
  value       = [aws_subnet.public.*.cidr_block]
}
output "subnet_app_ids" {
  description = "List of IDs of app subnets."
  value       = [aws_subnet.app.*.id]
}
output "subnet_app_cidr_blocks" {
  description = "List of cidr_blocks of app subnets."
  value       = [aws_subnet.app.*.cidr_block]
}
output "subnet_data_ids" {
  description = "List of IDs of data subnets."
  value       = [aws_subnet.data.*.id]
}
output "subnet_data_cidr_blocks" {
  description = "List of cidr_blocks of data subnets."
  value       = [aws_subnet.data.*.cidr_block]
}
```

### Module Version

0.7.0

### Terraform Version and Terraform AWS Provider Version

```
Terraform v0.12.30
+ provider.aws v3.35.0
```

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here.
# For large Terraform configs, please use a service like Google Drive and share a link to the ZIP file.
```

### Steps to Reproduce

1. `terraform apply`
2. `<any_command_you_executed>`

### References

* #0000

**Comment by puzzloholic** [comment]
For those waiting for the review, this is temporary workaround regarding output issue, wrap `flatten` for outputs that produce list of list

```
output "subnet_public_ids" {
  description = "List of IDs of public subnets."
  value       = flatten(module.eci_vpc_dev.subnet_public_ids)
}
```

Related PR https://github.com/traveloka/tvlk-eci-dev-terraform-aws/pull/5168
